# 2024.10.xx - v. 0.1 - initial release

clear

while : ; do
  echo co mam wygenerowac?
  read -t 500 wejscie
  clear
  echo $wejscie
  zmodyfikowany="$(echo $wejscie | sed 's|/|,|g'|sed 's|·|,|g')"

  echo
  echo
  echo
  echo "[speaker:Vicki] <prosody rate=\"50%\"/>$zmodyfikowany<break time=\"0.3s\"/>"
  echo "[speaker:Hans]                       $zmodyfikowany<prosody/>"
  echo
  echo
  first_string=$(echo "$wejscie" | cut -d' ' -f1)
  second_string=$(echo "$wejscie" | cut -d' ' -f2)
  noun=FALSE
  # Convert the variable to lowercase and check if it's one of the specified words
  if [[ "${first_string,,}" =~ ^(der|die|das)$ ]]; then
    noun=TRUE
    # Capitalize the first letter and keep the rest of the string as is
    second_string="${second_string^}"
  fi

  echo ; echo 
  if [ "$noun" = TRUE ];then
    echo "https://www.verbformen.de/deklination/substantive/?w=${second_string}"
    echo "https://www.verbformen.de/deklination/substantive/grundform/${first_string}_${second_string}.mp3"
    echo "https://www.verbformen.de/deklination/substantive/stammformen/${first_string}_${second_string}.mp3"
  else
    echo "https://www.verbformen.de/deklination/substantive/?w=${first_string}"
    echo "https://www.verbformen.de/deklination/adjektive/stammformen/${first_string}.mp3"

  fi
  echo
  echo ; echo 
  URL_1=""
  URL_2=""
  if [ "$noun" = TRUE ];then
    URL_1="https://www.verbformen.de/deklination/substantive/?w=${second_string}"
    URL_2="https://www.collinsdictionary.com/de/worterbuch/deutsch-englisch/${second_string}"
  else
    URL_1="https://www.verbformen.de/deklination/adjektive/?w=${first_string}"
    URL_2="https://www.collinsdictionary.com/de/worterbuch/deutsch-englisch/${first_string}"
  fi
  echo $URL_1
  echo $URL_2

  echo "(URLs above were generated by the script....)"
  echo 
  echo 
done
